'use client';
import { useState } from 'react';
import Button from '@/components/ui/button';
import Panel from '@/components/ui/panel';
import Badge from '@/components/ui/badge';
import { IMPORT_DEFINITIONS } from '@/lib/import/schema';
import type { ImportMode, ImportType } from '@/lib/import/types';

const types = Object.entries(IMPORT_DEFINITIONS) as [ImportType, (typeof IMPORT_DEFINITIONS)[ImportType]][];
export default function FileUploadPanel() {
  const [file, setFile] = useState<File | null>(null); const [type, setType] = useState<ImportType>('usage_history'); const [mode, setMode] = useState<ImportMode>('append'); const [mapping, setMapping] = useState<Record<string, string>>({}); const [result, setResult] = useState<any>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function preview() { if (!file) return setMessage('파일을 선택하세요.'); setBusy(true); setMessage(''); const form = new FormData(); form.append('file', file); form.append('importType', type); form.append('importMode', mode); if (Object.keys(mapping).length) form.append('mapping', JSON.stringify(mapping)); const response = await fetch('/api/admin/import/preview', { method: 'POST', body: form }); const data = await response.json(); setBusy(false); if (!response.ok) return setMessage(data.error ?? '검증에 실패했습니다.'); setResult(data); setMapping(data.mapping); }
  async function execute() { if (!result) return; setBusy(true); const response = await fetch('/api/admin/import/execute', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ batchId: result.batchId, confirmReplace: mode === 'replace' }) }); const data = await response.json(); setBusy(false); setMessage(response.ok ? `적재 완료: ${data.importedRows}건` : data.error); if (response.ok) setResult({ ...result, status: 'IMPORTED', imported: data }); }
  async function rollback() { if (!result?.batchId) return; const response = await fetch('/api/admin/import/rollback', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ batchId: result.batchId }) }); const data = await response.json(); setMessage(response.ok ? '배치 rollback이 완료되었습니다.' : data.error); }
  const definition = IMPORT_DEFINITIONS[type]; return <div className="import-stack"><Panel title="File Upload" meta="CSV / Excel · 최대 50,000행"><div className="import-controls"><label>파일<input className="form-input" type="file" accept=".csv,.xlsx" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setResult(null); }} /></label><label>데이터 종류<select className="form-input" value={type} onChange={(event) => { setType(event.target.value as ImportType); setResult(null); }}>{types.map(([key, item]) => <option key={key} value={key}>{item.label}</option>)}</select></label><label>Import Mode<select className="form-input" value={mode} onChange={(event) => { setMode(event.target.value as ImportMode); setResult(null); }}><option value="append">append</option><option value="upsert">upsert</option><option value="replace">replace (관리자 확인)</option></select></label></div><p className="muted import-flow">파일 선택 → Parse/Preview → Column Mapping → Validation → 사용자 확인 → Import</p><Button variant="primary" onClick={preview} disabled={busy || !file}>{busy ? '처리 중…' : 'Parse · Preview · Validation'}</Button>{message && <p className="text-danger">{message}</p>}</Panel>{result && <Panel title="Preview & Column Mapping" meta={<Badge status={result.status === 'VALIDATED' ? 'SAFE' : 'CRITICAL'}>{result.status}</Badge>}><p className="muted">Batch: {result.batchId} · {result.summary.totalRows.toLocaleString()}행</p><div className="mapping-grid">{Object.keys(definition.aliases).map((target) => <label key={target}>{target}<select className="form-input" value={mapping[target] ?? ''} onChange={(event) => setMapping({ ...mapping, [target]: event.target.value })}><option value="">매핑 안 함</option>{result.headers.map((header: string) => <option key={header} value={header}>{header}</option>)}</select></label>)}</div><p>성공 {result.summary.successRows} · 경고 {result.summary.warningRows} · 오류 {result.summary.errorRows}</p><div className="table-wrap"><table><thead><tr>{result.headers.map((header: string) => <th key={header}>{header}</th>)}</tr></thead><tbody>{result.preview.slice(0, 5).map((row: Record<string, unknown>, index: number) => <tr key={index}>{result.headers.map((header: string) => <td key={header}>{String(row[header] ?? '—')}</td>)}</tr>)}</tbody></table></div><div className="button-row import-actions"><Button onClick={preview} disabled={busy}>매핑 확인 후 재검증</Button><Button variant="primary" onClick={execute} disabled={busy || result.status !== 'VALIDATED' || result.summary.errorRows > 0}>사용자 확인 후 Import</Button><a className="button" href={`/api/admin/import/errors?batchId=${result.batchId}`}>오류 CSV</a>{result.status === 'IMPORTED' && result.imported?.rollbackSupported && <Button onClick={rollback}>이 배치 rollback</Button>}</div>{mode === 'replace' && <p className="callout">replace는 기존 대상 RAW를 삭제한 뒤 저장하며, 완전 rollback을 지원하지 않습니다.</p>}</Panel>}</div>;
}
