'use client';
import { useMemo, useState } from 'react';
import Badge from '@/components/ui/badge';
import EmptyValue from '@/components/ui/empty-value';
import type { SkuDemandProfile } from '@/lib/scm-model';

function number(value: number | null, digits = 2, suffix = '') { return value === null ? <EmptyValue reason="CALCULATION_UNAVAILABLE" /> : `${value.toFixed(digits)}${suffix}`; }
function demandStatus(value: SkuDemandProfile['demandType']) { return value ? <Badge status={value === 'SMOOTH' ? 'SAFE' : value === 'INTERMITTENT' ? 'WARNING' : 'CRITICAL'}>{value}</Badge> : <Badge status="CALCULATION_UNAVAILABLE" />; }
export default function DemandProfileTable({ rows }: { rows: SkuDemandProfile[] }) {
  const [type, setType] = useState('ALL'); const [availability, setAvailability] = useState('ALL'); const [search, setSearch] = useState('');
  const filtered = useMemo(() => rows.filter((row) => (type === 'ALL' || row.demandType === type) && (availability === 'ALL' || (availability === 'AVAILABLE' ? row.demandType !== null : row.demandType === null)) && `${row.itemId} ${row.itemName}`.toLowerCase().includes(search.toLowerCase())), [rows, type, availability, search]);
  return <><div className="demand-toolbar profile-toolbar"><div className="toolbar-group"><label htmlFor="profile-type">Demand Type</label><select id="profile-type" className="form-input" value={type} onChange={(event) => setType(event.target.value)}><option value="ALL">전체</option><option value="SMOOTH">SMOOTH</option><option value="INTERMITTENT">INTERMITTENT</option><option value="ERRATIC">ERRATIC</option><option value="LUMPY">LUMPY</option></select></div><div className="toolbar-group"><label htmlFor="profile-availability">계산 상태</label><select id="profile-availability" className="form-input" value={availability} onChange={(event) => setAvailability(event.target.value)}><option value="ALL">전체</option><option value="AVAILABLE">계산 가능</option><option value="UNAVAILABLE">계산 불가</option></select></div><div className="toolbar-group profile-search"><label htmlFor="profile-search">SKU 검색</label><input id="profile-search" className="form-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="SKU 또는 품목명" /></div></div><p className="muted profile-result-count">analytics 결과 {filtered.length.toLocaleString()}건</p><div className="analysis-table-wrap"><table className="analysis-table"><thead><tr><th>SKU</th><th>품목명</th><th>ADI</th><th>CV²</th><th>Zero-demand Rate</th><th>Trend</th><th>Demand Type</th><th>Seasonality</th><th>Reason</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.itemId}><td>{row.itemId}</td><td>{row.itemName}</td><td>{number(row.adi)}</td><td>{number(row.cvSquared)}</td><td>{number(row.zeroDemandRate, 1, '%')}</td><td>{number(row.trend)}</td><td>{demandStatus(row.demandType)}</td><td>{row.seasonality === null ? <EmptyValue reason="INSUFFICIENT_PERIODS" /> : row.seasonality ? 'TRUE' : 'FALSE'}</td><td>{row.reasonCode ?? '—'}</td></tr>)}{!filtered.length && <tr><td colSpan={9} className="muted">조건에 맞는 수요 프로파일이 없습니다.</td></tr>}</tbody></table></div></>;
}

