import type { ColumnMapping, ImportDefinition, ImportType, RawRow } from './types.ts';

const common = { item_id: ['item_id', 'item code', '품목코드', '품목id', '품목'], supplier_id: ['supplier_id', 'supplier code', '공급업체코드', '공급처코드', '공급업체'] };
export const IMPORT_DEFINITIONS: Record<ImportType, ImportDefinition> = {
  shipment_log: { label: 'Shipment Log', targetTable: 'shipment_log', required: ['shipment_id', 'item_id', 'ship_date', 'qty'], aliases: { shipment_id: ['shipment_id', 'shipment no', '출하번호'], ...common, ship_date: ['ship_date', '출하일', '출고일'], qty: ['qty', '수량', '출하수량'] }, numeric: ['qty'], dates: ['ship_date'], key: ['shipment_id'] },
  usage_history: { label: 'Usage History', targetTable: 'usage_history', required: ['item_id', 'use_date', 'qty'], aliases: { usage_id: ['usage_id', '사용이력id'], ...common, use_date: ['use_date', '출고일', '사용일', '사용일자'], qty: ['qty', '수량', '출고수량', '사용량'], warehouse: ['warehouse', '창고'], note: ['note', '비고'] }, numeric: ['qty'], dates: ['use_date'], key: ['usage_id', 'item_id', 'use_date'] },
  inventory: { label: 'Inventory', targetTable: 'inventory', required: ['item_id', 'warehouse', 'current_stock', 'base_date'], aliases: { ...common, item_id: ['item_id', 'item code', '품목코드'], warehouse: ['warehouse', '창고'], current_stock: ['current_stock', '현재고'], base_date: ['base_date', '기준일자', '기준일'], safety_stock: ['safety_stock', '안전재고'] }, numeric: ['current_stock', 'safety_stock'], dates: ['base_date'], key: ['item_id', 'warehouse', 'base_date'] },
  item_master: { label: 'Item Master', targetTable: 'item_master', required: ['item_id', 'item_name'], aliases: { item_id: ['item_id', 'item code', '품목코드'], item_name: ['item_name', '품목명'], item_type: ['item_type', '품목구분'], unit: ['unit', '단위'], unit_price: ['unit_price', '표준단가'], is_active: ['is_active', '사용여부'], supplier_id: common.supplier_id }, numeric: ['unit_price'], dates: [], key: ['item_id'] },
  supplier_master: { label: 'Supplier Master', targetTable: 'supplier_master', required: ['supplier_id', 'supplier_name'], aliases: { supplier_id: ['supplier_id', 'supplier code', '공급업체코드'], supplier_name: ['supplier_name', '공급업체명'], country: ['country', '국가'], standard_lead_time: ['standard_lead_time', '표준리드타임', '표준리드타임(일)'], contact: ['contact', '담당자'], is_active: ['is_active', '사용여부'] }, numeric: ['standard_lead_time'], dates: [], key: ['supplier_id'] },
  purchase_order: { label: 'Purchase Order', targetTable: 'purchase_order', required: ['po_no', 'order_date', 'supplier_id', 'item_id', 'order_qty'], aliases: { po_no: ['po_no', '발주번호'], order_date: ['order_date', '발주일'], supplier_id: common.supplier_id, item_id: common.item_id, order_qty: ['order_qty', '발주수량'], unit_price: ['unit_price', '단가'], due_date: ['due_date', '납기예정일'], ordered_by: ['ordered_by', '발주담당'] }, numeric: ['order_qty', 'unit_price'], dates: ['order_date', 'due_date'], key: ['po_no', 'item_id'] },
  goods_receipt: { label: 'Goods Receipt', targetTable: 'goods_receipt', required: ['receipt_no', 'item_id', 'receipt_qty', 'receipt_date'], aliases: { receipt_no: ['receipt_no', '입고번호'], po_no: ['po_no', '발주번호'], item_id: common.item_id, receipt_qty: ['receipt_qty', '입고수량'], receipt_date: ['receipt_date', '입고일'], warehouse: ['warehouse', '입고창고'] }, numeric: ['receipt_qty'], dates: ['receipt_date'], key: ['receipt_no'] },
  sales_order: { label: 'Sales Order', targetTable: 'sales_order', required: ['sales_order_id', 'order_date', 'item_id', 'quantity'], aliases: { sales_order_id: ['sales_order_id', '판매주문번호'], order_date: ['order_date', '주문일'], customer_id: ['customer_id', '고객코드'], item_id: common.item_id, quantity: ['quantity', '수량', '주문수량'], status: ['status', '상태'], expected_delivery_date: ['expected_delivery_date', '납기예정일'] }, numeric: ['quantity'], dates: ['order_date', 'expected_delivery_date'], key: ['sales_order_id', 'item_id'] },
  business_event: { label: 'Business Event', targetTable: 'business_event', required: ['business_event_id', 'event_type', 'event_date'], aliases: { business_event_id: ['business_event_id', '이벤트id'], event_type: ['event_type', '이벤트유형'], event_date: ['event_date', '이벤트일'], item_id: common.item_id, qty: ['qty', '수량'], description: ['description', '설명', '비고'] }, numeric: ['qty'], dates: ['event_date'], key: ['business_event_id'] },
  item_substitute: { label: 'Item Substitute', targetTable: 'item_substitute', required: ['item_id', 'substitute_item_id'], aliases: { item_id: common.item_id, substitute_item_id: ['substitute_item_id', '대체품목코드'], conversion_rate: ['conversion_rate', '환산율'], priority: ['priority', '우선순위'], active: ['active', '사용여부'] }, numeric: ['conversion_rate', 'priority'], dates: [], key: ['item_id', 'substitute_item_id'] },
};

const normalize = (value: string) => value.trim().toLowerCase().replace(/[\s_\-()]/g, '');
export function inferMapping(headers: string[], importType: ImportType): ColumnMapping {
  const definition = IMPORT_DEFINITIONS[importType]; const result: ColumnMapping = {};
  for (const target of Object.keys(definition.aliases)) { const alias = definition.aliases[target].find((candidate) => headers.some((header) => normalize(header) === normalize(candidate))); if (alias) result[target] = headers.find((header) => normalize(header) === normalize(alias))!; }
  return result;
}
export function mapRows(rows: RawRow[], mapping: ColumnMapping): RawRow[] { return rows.map((row) => Object.fromEntries(Object.entries(mapping).map(([target, source]) => [target, row[source] ?? null]))); }
