import { requireUser } from '@/lib/auth';
import { getPurchaseRecommendations } from '@/lib/scm';
import AnalysisFrame from '@/components/analysis/analysis-frame';
import Panel from '@/components/ui/panel';
import Badge from '@/components/ui/badge';
import EmptyValue from '@/components/ui/empty-value';
export const dynamic = 'force-dynamic';
const n = (value: number | null) => value === null ? <EmptyValue reason="CALCULATION_UNAVAILABLE" /> : value.toLocaleString('ko-KR', { maximumFractionDigits: 1 });
export default async function PurchaseRecommendationPage() { await requireUser(); const { rows, error } = await getPurchaseRecommendations(); return <AnalysisFrame title="Purchase Recommendation" description="Safety Stock, Forecast, 확정수주, 재고와 정책값을 결합한 발주 추천입니다."><Panel title="SKU별 발주 추천">{error ? <p className="text-danger">조회에 실패했습니다: {error}</p> : <div className="analysis-table-wrap"><table className="analysis-table"><thead><tr>{['SKU','품목명','Risk','Forecast','확정수주','Inventory','Safety Stock','Stockout','Required','MOQ','Pack','Recommended','권고일'].map((x) => <th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.itemId}><td>{row.itemId}</td><td>{row.itemName}</td><td><Badge status={row.riskStatus === 'CRITICAL' ? 'CRITICAL' : row.riskStatus === 'WARNING' ? 'WARNING' : row.calculationStatus === 'CALCULATION_UNAVAILABLE' ? 'CALCULATION_UNAVAILABLE' : 'SAFE'}>{row.riskStatus ?? row.calculationStatus}</Badge></td><td>{n(row.forecastQty)}</td><td>{n(row.confirmedOrderQty)}</td><td>{n(row.availableInventory)}</td><td>{n(row.safetyStock)}</td><td>{row.stockoutDate ?? <EmptyValue reason="NO_STOCKOUT_DATE" />}</td><td>{n(row.requiredQty)}</td><td>{n(row.moq)}</td><td>{n(row.packSize)}</td><td>{n(row.recommendedQty)}</td><td>{row.recommendedOrderDate ?? <EmptyValue reason={row.reasonCode ?? 'NOT_AVAILABLE'} />}</td></tr>)}{!rows.length && <tr><td colSpan={13} className="muted">발주 추천 데이터가 없습니다.</td></tr>}</tbody></table></div>}</Panel></AnalysisFrame>; }
