-- STEP7 Backtest: forecast_result + core.v_test_actual만 사용합니다.
-- Bias는 forecast - actual로 정의합니다. 양수=과대예측, 음수=과소예측.
alter table core.forecast_setting add column if not exists champion_metric text not null default 'WAPE';
alter table core.forecast_setting add column if not exists reference_model_id text not null default 'MA_3M';
alter table core.forecast_setting drop constraint if exists forecast_setting_champion_metric_check;
alter table core.forecast_setting add constraint forecast_setting_champion_metric_check check (champion_metric in ('WAPE','MAPE','BIAS','RMSE','MAE'));

create table if not exists core.backtest_run (
  backtest_run_id uuid primary key default gen_random_uuid(), forecast_run_id uuid not null references core.forecast_run(run_id),
  test_start date not null, test_end date not null, metric text not null default 'WAPE', status text not null default 'RUNNING' check (status in ('RUNNING','SUCCESS','FAILED')),
  started_at timestamptz not null default now(), finished_at timestamptz, triggered_by uuid references auth.users(id) on delete set null, message text
);
create table if not exists core.model_performance (
  backtest_run_id uuid not null references core.backtest_run(backtest_run_id) on delete cascade, run_id uuid not null references core.forecast_run(run_id) on delete cascade,
  model_id text not null, model_version text, item_id text not null, n_periods integer not null default 0,
  wape numeric, mape numeric, bias numeric, rmse numeric, mae numeric, baseline_improvement numeric, rank integer,
  calculation_status text not null default 'SUCCESS' check (calculation_status in ('SUCCESS','CALCULATION_UNAVAILABLE')), reason_code text, calculated_at timestamptz not null default now(),
  primary key(backtest_run_id, model_id, item_id)
);
create table if not exists core.champion_model (
  champion_id bigint generated by default as identity primary key, item_id text not null, champion_model_id text not null, model_version text,
  champion_metric text not null, champion_metric_value numeric, wape numeric, mape numeric, bias numeric, rmse numeric,
  candidate_performance jsonb not null default '[]'::jsonb, selection_reason text not null, selection_method text not null check (selection_method in ('AUTO','MANUAL')),
  selected_at timestamptz not null default now(), selected_by uuid references auth.users(id) on delete set null, backtest_run_id uuid references core.backtest_run(backtest_run_id),
  reason_code text
);
create index if not exists model_performance_run_item_idx on core.model_performance(backtest_run_id, item_id);
create index if not exists champion_item_idx on core.champion_model(item_id, selected_at desc);

create or replace view analytics.v_model_performance as select * from core.model_performance;
create or replace view analytics.v_champion_model as select distinct on (item_id) * from core.champion_model order by item_id, selected_at desc, champion_id desc;
create or replace view analytics.v_backtest_run as select * from core.backtest_run;
create or replace view analytics.v_model_comparison as
select fr.run_id, fr.model_id, fr.item_id, fr.period, fr.model_version, fr.p50, fr.p80, fr.p90, fr.predicted_qty,
       ta.use_date as actual_period, ta.qty as actual_qty, mp.backtest_run_id, mp.wape, mp.mape, mp.bias, mp.rmse, mp.mae, mp.rank,
       cm.champion_model_id = fr.model_id as is_champion
from core.forecast_result fr
left join core.v_test_actual ta on ta.item_id = fr.item_id and ta.use_date = fr.period
left join core.model_performance mp on mp.run_id = fr.run_id and mp.model_id = fr.model_id and mp.item_id = fr.item_id
left join lateral (select c.champion_model_id from core.champion_model c where c.item_id = fr.item_id order by c.selected_at desc, c.champion_id desc limit 1) cm on true;

create or replace function core.run_backtest(p_forecast_run_id uuid default null)
returns uuid language plpgsql security definer set search_path = core, public as $$
declare
  r core.forecast_run%rowtype; s core.forecast_setting%rowtype; b uuid := gen_random_uuid(); actor uuid := auth.uid();
begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select * into s from core.forecast_setting where setting_key='default';
  select * into r from core.forecast_run where run_id = coalesce(p_forecast_run_id, (select run_id from core.forecast_run order by started_at desc limit 1));
  if r.run_id is null then raise exception 'FORECAST_RUN_NOT_FOUND'; end if;
  if s.test_start is null or s.test_end is null then raise exception 'TEST_SETTING_INCOMPLETE'; end if;
  insert into core.backtest_run(backtest_run_id, forecast_run_id, test_start, test_end, metric, triggered_by) values(b, r.run_id, s.test_start, s.test_end, s.champion_metric, actor);
  begin
    with pairs as (
      select fr.model_id, fr.model_version, fr.item_id, fr.period, fr.predicted_qty, ta.qty actual_qty
      from core.forecast_result fr join core.v_test_actual ta on ta.item_id=fr.item_id and ta.use_date=fr.period where fr.run_id=r.run_id and fr.period between s.test_start and s.test_end
    ), agg as (
      select model_id, max(model_version) model_version, item_id, count(*) filter(where actual_qty is not null and predicted_qty is not null)::int n_periods,
        case when sum(abs(actual_qty)) filter(where actual_qty is not null and predicted_qty is not null) > 0 then sum(abs(predicted_qty-actual_qty)) filter(where actual_qty is not null and predicted_qty is not null) / sum(abs(actual_qty)) filter(where actual_qty is not null and predicted_qty is not null) end wape,
        case when count(*) filter(where actual_qty <> 0 and actual_qty is not null and predicted_qty is not null) > 0 then avg(abs(predicted_qty-actual_qty)/abs(actual_qty)) filter(where actual_qty <> 0 and actual_qty is not null and predicted_qty is not null) end mape,
        avg(predicted_qty-actual_qty) filter(where actual_qty is not null and predicted_qty is not null) bias,
        case when count(*) filter(where actual_qty is not null and predicted_qty is not null) > 0 then sqrt(avg((predicted_qty-actual_qty)^2) filter(where actual_qty is not null and predicted_qty is not null)) end rmse,
        avg(abs(predicted_qty-actual_qty)) filter(where actual_qty is not null and predicted_qty is not null) mae
      from pairs group by model_id,item_id
    ), ranked as (
      select a.*, rank() over(partition by item_id order by case s.champion_metric when 'WAPE' then wape when 'MAPE' then mape when 'RMSE' then rmse when 'MAE' then mae when 'BIAS' then abs(bias) end nulls last, abs(bias) nulls last, rmse nulls last, model_id) rank_no
      from agg a
    ), refs as (select item_id, case s.champion_metric when 'WAPE' then wape when 'MAPE' then mape when 'RMSE' then rmse when 'MAE' then mae when 'BIAS' then abs(bias) end ref_metric from ranked where model_id=s.reference_model_id)
    insert into core.model_performance(backtest_run_id,run_id,model_id,model_version,item_id,n_periods,wape,mape,bias,rmse,mae,baseline_improvement,rank,calculation_status,reason_code)
    select b,r.run_id,x.model_id,x.model_version,x.item_id,x.n_periods,x.wape,x.mape,x.bias,x.rmse,x.mae,
      case when refs.ref_metric is not null and (case s.champion_metric when 'WAPE' then x.wape when 'MAPE' then x.mape when 'RMSE' then x.rmse when 'MAE' then x.mae when 'BIAS' then abs(x.bias) end) is not null and refs.ref_metric <> 0 then 1-((case s.champion_metric when 'WAPE' then x.wape when 'MAPE' then x.mape when 'RMSE' then x.rmse when 'MAE' then x.mae when 'BIAS' then abs(x.bias) end)/refs.ref_metric) end,
      case when x.wape is null and x.mape is null and x.rmse is null and x.mae is null then null else x.rank_no end,
      case when x.n_periods=0 then 'CALCULATION_UNAVAILABLE' when s.champion_metric='WAPE' and x.wape is null then 'CALCULATION_UNAVAILABLE' when s.champion_metric='MAPE' and x.mape is null then 'CALCULATION_UNAVAILABLE' else 'SUCCESS' end,
      case when x.n_periods=0 then 'NO_COMPARABLE_PERIODS' when s.champion_metric='WAPE' and x.wape is null then 'ACTUAL_SUM_ZERO' when s.champion_metric='MAPE' and x.mape is null then 'MAPE_DENOMINATOR_ZERO' end
    from ranked x left join refs using(item_id);
    insert into core.champion_model(item_id,champion_model_id,model_version,champion_metric,champion_metric_value,wape,mape,bias,rmse,candidate_performance,selection_reason,selection_method,selected_by,backtest_run_id,reason_code)
    select x.item_id,x.model_id,x.model_version,s.champion_metric,case s.champion_metric when 'WAPE' then x.wape when 'MAPE' then x.mape when 'RMSE' then x.rmse when 'MAE' then x.mae when 'BIAS' then abs(x.bias) end,x.wape,x.mape,x.bias,x.rmse,
      (select jsonb_agg(to_jsonb(p) order by p.rank, p.model_id) from core.model_performance p where p.backtest_run_id=b and p.item_id=x.item_id), '자동 지표 최상위 모델', 'AUTO', actor, b, null
    from core.model_performance x where x.backtest_run_id=b and x.rank=1 and x.calculation_status='SUCCESS';
    update core.backtest_run set status='SUCCESS', finished_at=clock_timestamp(), message='BACKTEST_SUCCESS' where backtest_run_id=b;
  exception when others then update core.backtest_run set status='FAILED', finished_at=clock_timestamp(), message=sqlerrm where backtest_run_id=b; end;
  return b;
end $$;

create or replace function core.set_manual_champion(p_item_id text, p_model_id text, p_reason text)
returns void language plpgsql security definer set search_path=core,public as $$ declare actor uuid:=auth.uid(); perf core.model_performance%rowtype; metric text; begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED'; end if; if nullif(trim(p_reason),'') is null then raise exception 'CHAMPION_REASON_REQUIRED'; end if;
  select champion_metric into metric from core.forecast_setting where setting_key='default';
  select * into perf from core.model_performance where item_id=p_item_id and model_id=p_model_id order by calculated_at desc limit 1;
  if perf.item_id is null then raise exception 'CHAMPION_CANDIDATE_NOT_FOUND'; end if;
  insert into core.champion_model(item_id,champion_model_id,model_version,champion_metric,champion_metric_value,wape,mape,bias,rmse,candidate_performance,selection_reason,selection_method,selected_by,backtest_run_id)
  select perf.item_id,perf.model_id,perf.model_version,metric,case metric when 'WAPE' then perf.wape when 'MAPE' then perf.mape when 'RMSE' then perf.rmse when 'MAE' then perf.mae when 'BIAS' then abs(perf.bias) end,perf.wape,perf.mape,perf.bias,perf.rmse,(select jsonb_agg(to_jsonb(p)) from core.model_performance p where p.backtest_run_id=perf.backtest_run_id and p.item_id=perf.item_id),p_reason,'MANUAL',actor,perf.backtest_run_id;
  insert into core.audit_log(actor,action,target_type,target_id,before,after) values(actor,'CHAMPION_MANUAL_CHANGE','champion_model',p_item_id,null,jsonb_build_object('model_id',p_model_id,'reason',p_reason));
end $$;

alter table core.backtest_run enable row level security; alter table core.model_performance enable row level security; alter table core.champion_model enable row level security;
drop policy if exists backtest_run_authenticated_select on core.backtest_run; create policy backtest_run_authenticated_select on core.backtest_run for select to authenticated using(true);
drop policy if exists model_performance_authenticated_select on core.model_performance; create policy model_performance_authenticated_select on core.model_performance for select to authenticated using(true);
drop policy if exists champion_authenticated_select on core.champion_model; create policy champion_authenticated_select on core.champion_model for select to authenticated using(true);
drop policy if exists champion_admin_write on core.champion_model; create policy champion_admin_write on core.champion_model for all to authenticated using(core.is_admin()) with check(core.is_admin());
grant select on analytics.v_model_performance,analytics.v_champion_model,analytics.v_backtest_run,analytics.v_model_comparison to authenticated;
grant select on core.backtest_run,core.model_performance,core.champion_model to authenticated;
grant execute on function core.run_backtest(uuid),core.set_manual_champion(text,text,text) to authenticated;
revoke all on analytics.v_model_performance,analytics.v_champion_model,analytics.v_backtest_run,analytics.v_model_comparison from anon;
