-- STEP4 파일 적재 파이프라인: staging → validation → 승인 import

create table if not exists core.column_mapping (
  id bigint generated by default as identity primary key,
  import_type text not null,
  source_column text not null,
  target_column text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (import_type, source_column)
);

create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(),
  file_name text not null,
  import_type text not null check (import_type in ('shipment_log', 'usage_history', 'inventory', 'item_master', 'supplier_master', 'purchase_order', 'goods_receipt', 'sales_order', 'business_event', 'item_substitute')),
  import_mode text not null check (import_mode in ('append', 'upsert', 'replace')),
  mapping jsonb not null default '{}'::jsonb,
  total_rows integer not null default 0,
  success_rows integer not null default 0,
  warning_rows integer not null default 0,
  error_rows integer not null default 0,
  status text not null default 'STAGED' check (status in ('STAGED', 'VALIDATED', 'VALIDATION_FAILED', 'IMPORTED', 'ROLLED_BACK', 'ROLLBACK_UNAVAILABLE', 'FAILED')),
  uploaded_by uuid not null references auth.users(id) on delete restrict,
  uploaded_at timestamptz not null default now(),
  imported_at timestamptz,
  rollback_supported boolean not null default true,
  forecast_stale boolean not null default false
);

create table if not exists core.import_staging (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  original_record jsonb not null,
  mapped_record jsonb not null default '{}'::jsonb,
  validation_status text not null default 'PENDING' check (validation_status in ('PENDING', 'SUCCESS', 'WARNING', 'ERROR')),
  unique (batch_id, row_number)
);

create table if not exists core.validation_error (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  field_name text,
  error_code text not null,
  error_message text not null,
  severity text not null check (severity in ('WARNING', 'ERROR')),
  original_value text,
  created_at timestamptz not null default now()
);

create table if not exists core.forecast_data_state (
  state_key text primary key default 'default',
  data_snapshot_at timestamptz,
  stale boolean not null default false,
  stale_reason text,
  updated_at timestamptz not null default now()
);
insert into core.forecast_data_state(state_key) values ('default') on conflict (state_key) do nothing;

create index if not exists upload_batch_uploaded_at_idx on core.upload_batch(uploaded_at desc);
create index if not exists import_staging_batch_idx on core.import_staging(batch_id);
create index if not exists validation_error_batch_idx on core.validation_error(batch_id, severity, row_number);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'shipment_log', 'usage_history', 'inventory', 'item_master',
    'supplier_master', 'purchase_order', 'goods_receipt',
    'business_event', 'sales_order', 'item_substitute'
  ] loop
    execute format('create unique index if not exists %I on raw.%I (source_type, source_record_id) where source_record_id is not null', table_name || '_source_record_uidx', table_name);
  end loop;
end $$;

create or replace function core.rollback_import_batch(p_batch_id uuid)
returns text
language plpgsql
security definer
set search_path = core, raw, public
as $$
declare
  batch core.upload_batch%rowtype;
  target_table text;
begin
  select * into batch from core.upload_batch where batch_id = p_batch_id for update;
  if not found then raise exception 'BATCH_NOT_FOUND'; end if;
  if batch.import_mode = 'replace' or not batch.rollback_supported then raise exception 'REPLACE_ROLLBACK_UNAVAILABLE'; end if;
  target_table := batch.import_type;
  if target_table not in ('shipment_log', 'usage_history', 'inventory', 'item_master', 'supplier_master', 'purchase_order', 'goods_receipt', 'business_event', 'sales_order', 'item_substitute') then raise exception 'IMPORT_TYPE_NOT_ALLOWED'; end if;
  execute format('delete from raw.%I where batch_id = $1', target_table) using p_batch_id;
  update core.upload_batch set status = 'ROLLED_BACK', rollback_supported = false where batch_id = p_batch_id;
  return 'ROLLED_BACK';
end;
$$;

create or replace function core.replace_import_target(p_import_type text)
returns text
language plpgsql
security definer
set search_path = core, raw, public
as $$
begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if p_import_type not in ('shipment_log', 'usage_history', 'inventory', 'item_master', 'supplier_master', 'purchase_order', 'goods_receipt', 'business_event', 'sales_order', 'item_substitute') then
    raise exception 'IMPORT_TYPE_NOT_ALLOWED';
  end if;
  execute format('delete from raw.%I', p_import_type);
  return 'REPLACED';
end;
$$;

alter table core.column_mapping enable row level security;
alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.validation_error enable row level security;
alter table core.forecast_data_state enable row level security;

create policy "column_mapping_admin_all" on core.column_mapping for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy "upload_batch_admin_all" on core.upload_batch for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy "import_staging_admin_all" on core.import_staging for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy "validation_error_admin_all" on core.validation_error for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy "forecast_data_state_authenticated_select" on core.forecast_data_state for select to authenticated using (true);
create policy "forecast_data_state_admin_update" on core.forecast_data_state for update to authenticated using (core.is_admin()) with check (core.is_admin());

grant select, insert, update, delete on core.column_mapping, core.upload_batch, core.import_staging, core.validation_error, core.forecast_data_state to authenticated;
grant usage, select on all sequences in schema core to authenticated;
grant execute on function core.rollback_import_batch(uuid) to authenticated;
grant execute on function core.replace_import_target(text) to authenticated;

-- raw는 ADMIN import 과정에서만 쓰며, 일반 USER와 anon은 접근하지 않습니다.
grant insert, update, delete on all tables in schema raw to authenticated;
do $$
declare table_name text;
begin
  foreach table_name in array array[
    'shipment_log', 'usage_history', 'inventory', 'item_master',
    'supplier_master', 'purchase_order', 'goods_receipt',
    'business_event', 'sales_order', 'item_substitute'
  ] loop
    execute format('drop policy if exists "import_admin_insert" on raw.%I', table_name);
    execute format('create policy "import_admin_insert" on raw.%I for insert to authenticated with check (core.is_admin())', table_name);
    execute format('drop policy if exists "import_admin_update" on raw.%I', table_name);
    execute format('create policy "import_admin_update" on raw.%I for update to authenticated using (core.is_admin()) with check (core.is_admin())', table_name);
    execute format('drop policy if exists "import_admin_delete" on raw.%I', table_name);
    execute format('create policy "import_admin_delete" on raw.%I for delete to authenticated using (core.is_admin())', table_name);
  end loop;
end $$;

create or replace view analytics.v_import_history as
select
  b.batch_id, b.file_name, b.import_type, b.import_mode, b.mapping,
  b.total_rows, b.success_rows, b.warning_rows, b.error_rows,
  b.status, b.uploaded_by, b.uploaded_at, b.imported_at,
  b.rollback_supported, b.forecast_stale,
  s.email as uploaded_by_email
from core.upload_batch b
left join auth.users s on s.id = b.uploaded_by;

grant select on analytics.v_import_history to authenticated;
revoke all on analytics.v_import_history from anon;
