-- STEP9: Forecast 기반 Inventory Projection
-- 원본 RAW는 수정하지 않고 기존 정제 view와 core.v_test_actual 외의 검증 실적을 사용하지 않습니다.

create table if not exists core.leadtime_policy_history (
  history_id bigint generated by default as identity primary key,
  supplier_id text not null, before_value jsonb, after_value jsonb not null,
  changed_by uuid references auth.users(id) on delete set null, changed_at timestamptz not null default now()
);
create index if not exists leadtime_policy_history_supplier_idx on core.leadtime_policy_history(supplier_id, changed_at desc);

create table if not exists core.soft_allocation (
  allocation_id uuid primary key default gen_random_uuid(), item_id text not null, allocation_period date not null,
  quantity numeric not null check (quantity >= 0), status text not null default 'ACTIVE', created_at timestamptz not null default now(), created_by uuid references auth.users(id) on delete set null
);

create or replace function core.record_leadtime_policy_history() returns trigger language plpgsql security definer set search_path=core,public as $$
begin
  insert into core.leadtime_policy_history(supplier_id,before_value,after_value,changed_by)
  values(coalesce(new.supplier_id,old.supplier_id),case when tg_op='INSERT' then null else to_jsonb(old) end,to_jsonb(new),auth.uid());
  return new;
end $$;
drop trigger if exists leadtime_policy_history_trigger on core.leadtime_plan;
create trigger leadtime_policy_history_trigger after insert or update on core.leadtime_plan for each row execute function core.record_leadtime_policy_history();

create or replace view core.v_leadtime_effective as
select st.supplier_id, st.supplier_name, st.country, st.n_samples, st.p80_days,
       p.planned_lead_time, coalesce(p.planned_lead_time, st.p80_days) effective_lead_time,
       case when p.planned_lead_time is not null then 'CONFIRMED' else 'P80_FALLBACK' end source,
       st.p50_days, st.p90_days, st.std_days, p.confirmed_at, p.confirmed_reason
from core.v_leadtime_stat st left join core.leadtime_plan p using(supplier_id);

create or replace view analytics.v_leadtime_policy as
select e.*, (select max(h.changed_at) from core.leadtime_policy_history h where h.supplier_id=e.supplier_id) last_changed_at,
       (select h.changed_by from core.leadtime_policy_history h where h.supplier_id=e.supplier_id order by h.changed_at desc limit 1) last_changed_by
from core.v_leadtime_effective e;

create or replace view core.v_projection_inventory as
with recursive setting as (select * from core.forecast_setting where setting_key='default'), periods as (
  select generate_series(date_trunc('month',current_date)::date, date_trunc('month',current_date)::date + make_interval(months => greatest(coalesce((select forecast_horizon from core.forecast_setting where setting_key='default'),3)-1,0)), interval '1 month')::date period
), items as (
  select item_id, item_name, supplier_id from core.v_item_master where is_active='Y'
), inventory as (
  select i.item_id, s.current_stock, s.current_stock is not null inventory_exists from items i left join core.v_stock_on_hand s using(item_id)
), champion_forecast as (
  select r.item_id, r.period, r.p50 as forecast_demand
  from core.forecast_result r join lateral (select c.champion_model_id,c.backtest_run_id from core.champion_model c where c.item_id=r.item_id order by c.selected_at desc,c.champion_id desc limit 1) c on c.champion_model_id=r.model_id and c.backtest_run_id=r.run_id
), receipts as (
  select upper(regexp_replace("품목코드", '[\s\-_]', '', 'g')) item_id,
    case when "납기예정일" ~ '^\d{4}[-/]\d{1,2}[-/]\d{1,2}$' then to_date(replace("납기예정일",'/','-'),'YYYY-MM-DD') when "납기예정일" ~ '^\d{1,2}-[A-Za-z]{3}-\d{2}$' then to_date("납기예정일",'DD-MON-YY') end receipt_date,
    nullif(replace("발주수량",',',''),'')::numeric quantity from raw.purchase_order
), confirmed_orders as (
  select upper(regexp_replace(item_id, '[\s\-_]', '', 'g')) item_id, date_trunc('month',expected_delivery_date)::date period, sum(quantity) quantity
  from raw.sales_order where upper(coalesce(status,'')) in ('CONFIRMED','확정','CONFIRMED_SALES') and expected_delivery_date is not null group by 1,2
), allocations as (
  select upper(regexp_replace(item_id, '[\s\-_]', '', 'g')) item_id, date_trunc('month',allocation_period)::date period, sum(quantity) quantity
  from core.soft_allocation where upper(status)='ACTIVE' group by 1,2
), inputs as (
  select i.item_id,i.item_name,i.supplier_id,p.period,inv.current_stock,inv.inventory_exists,
    coalesce((select sum(r.quantity) from receipts r where r.item_id=i.item_id and date_trunc('month',r.receipt_date)=p.period),0) scheduled_receipts,
    coalesce(o.quantity,0) confirmed_sales_order, coalesce(a.quantity,0) soft_allocation, f.forecast_demand,
    le.effective_lead_time, le.p80_days, le.p50_days, le.p90_days
  from items i cross join periods p join inventory inv using(item_id) left join champion_forecast f on f.item_id=i.item_id and f.period=p.period left join confirmed_orders o on o.item_id=i.item_id and o.period=p.period left join allocations a on a.item_id=i.item_id and a.period=p.period left join core.v_leadtime_effective le on le.supplier_id=i.supplier_id
), projection as (
  select x.*, row_number() over(partition by item_id order by period) period_number from inputs x
), recursive_projection as (
  select p.*, p.current_stock beginning_inventory, case when p.inventory_exists and p.forecast_demand is not null then p.current_stock + p.scheduled_receipts - p.soft_allocation - p.confirmed_sales_order - p.forecast_demand end ending_projected_inventory
  from projection p where p.period_number=1
  union all
  select p.*, r.ending_projected_inventory beginning_inventory, case when r.ending_projected_inventory is not null and p.forecast_demand is not null then r.ending_projected_inventory + p.scheduled_receipts - p.soft_allocation - p.confirmed_sales_order - p.forecast_demand end ending_projected_inventory
  from recursive_projection r join projection p on p.item_id=r.item_id and p.period_number=r.period_number+1
)
select *, case when ending_projected_inventory is not null and ending_projected_inventory <= 0 then period end stockout_period,
  case when effective_lead_time is null then 'NO_LEADTIME' when not inventory_exists then 'NO_INVENTORY_DATA' when forecast_demand is null then 'NO_FORECAST' end reason_code
from recursive_projection;

create or replace view analytics.v_inventory_projection as select * from core.v_projection_inventory;

create or replace view analytics.v_stockout_risk as
with summary as (
  select p.item_id,p.item_name,p.supplier_id,max(p.current_stock) current_stock,
    sum(p.scheduled_receipts) scheduled_receipts,sum(p.confirmed_sales_order) confirmed_sales_order,sum(p.soft_allocation) soft_allocation,
    min(p.effective_lead_time) effective_lead_time,min(p.p80_days) p80_days,min(p.p50_days) p50_days,min(p.p90_days) p90_days,
    min(p.period) first_period,min(p.stockout_period) stockout_period,
    min(p.period) filter(where p.forecast_demand is not null) forecast_start,
    max(p.period_number) filter(where p.ending_projected_inventory is not null) projected_periods,
    bool_or(not p.inventory_exists) inventory_missing,bool_or(p.forecast_demand is null) forecast_missing
  from core.v_projection_inventory p group by p.item_id,p.item_name,p.supplier_id
), result as (
 select s.*, case when s.current_stock is null or s.inventory_missing then 'CALCULATION_UNAVAILABLE' when s.effective_lead_time is null then 'CALCULATION_UNAVAILABLE' when s.forecast_missing then 'CALCULATION_UNAVAILABLE' when s.stockout_period is null then 'SAFE' when s.stockout_period <= (s.first_period + make_interval(days=>s.effective_lead_time))::date then 'CRITICAL' else 'WARNING' end risk_status,
  case when s.stockout_period is null or s.first_period is null then null else greatest(0,(s.stockout_period-s.first_period))::numeric end months_of_supply,
  case when s.stockout_period is null or s.first_period is null then null else greatest(0,(s.stockout_period-s.first_period)*30)::numeric end stockout_days,
  case when s.stockout_period is null then null else s.stockout_period end stockout_date,
  case when s.current_stock is null or s.inventory_missing then 'NO_INVENTORY_DATA' when s.effective_lead_time is null then 'NO_LEADTIME' when s.forecast_missing then 'NO_FORECAST' when s.stockout_period is null then null else null end reason
 from summary s)
select item_id,item_name,supplier_id,current_stock,scheduled_receipts inbound_qty,(current_stock) available_qty,null::numeric daily_usage_avg,null::numeric cv,effective_lead_time planned_lead_time,stockout_days,stockout_date,risk_status,reason,scheduled_receipts,confirmed_sales_order,soft_allocation,months_of_supply,stockout_period,effective_lead_time,p80_days,p50_days,p90_days
from result;

create or replace view analytics.v_stockout_kpi as select count(*)::bigint n_items,count(*) filter(where risk_status='CRITICAL')::bigint n_critical,count(*) filter(where risk_status='SAFE')::bigint n_safe,count(*) filter(where risk_status='CALCULATION_UNAVAILABLE')::bigint n_unknown,count(*) filter(where stockout_days <= 30)::bigint n_within_30d,round(avg(stockout_days),1) avg_stockout_days,count(*) filter(where risk_status='WARNING')::bigint n_warning from analytics.v_stockout_risk;

alter table core.leadtime_policy_history enable row level security; alter table core.soft_allocation enable row level security;
drop policy if exists leadtime_history_authenticated_select on core.leadtime_policy_history; create policy leadtime_history_authenticated_select on core.leadtime_policy_history for select to authenticated using(true);
drop policy if exists soft_allocation_authenticated_select on core.soft_allocation; create policy soft_allocation_authenticated_select on core.soft_allocation for select to authenticated using(true);
drop policy if exists soft_allocation_admin_write on core.soft_allocation; create policy soft_allocation_admin_write on core.soft_allocation for all to authenticated using(core.is_admin()) with check(core.is_admin());
grant select on analytics.v_inventory_projection,analytics.v_stockout_risk,analytics.v_stockout_kpi,analytics.v_leadtime_policy to authenticated;
grant select on core.v_projection_inventory,core.leadtime_policy_history,core.soft_allocation to authenticated;
revoke all on analytics.v_inventory_projection,analytics.v_stockout_risk,analytics.v_stockout_kpi,analytics.v_leadtime_policy from anon;
