-- STEP6 SQL Baseline Forecast Engine
-- 학습 원천은 core.v_train_demand뿐이며 raw.usage_history/core.v_test_actual을 참조하지 않습니다.

alter table core.forecast_setting
  add column if not exists forecast_horizon integer not null default 3;
alter table core.forecast_setting
  drop constraint if exists forecast_setting_forecast_horizon_check;
alter table core.forecast_setting
  add constraint forecast_setting_forecast_horizon_check check (forecast_horizon > 0 and forecast_horizon <= 36);

create table if not exists core.model_config (
  model_id text primary key,
  model_name text not null,
  family text not null,
  engine text not null default 'SQL_BASELINE',
  version text not null,
  enabled boolean not null default true,
  is_default boolean not null default false,
  applicable_demand_type text[] not null default array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'],
  parameters jsonb not null default '{}'::jsonb,
  description text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  check (family in ('MOVING_AVERAGE','WEIGHTED_MOVING_AVERAGE','SEASONAL_NAIVE')),
  check (engine = 'SQL_BASELINE'),
  check (applicable_demand_type <@ array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY']::text[])
);

insert into core.model_config(model_id, model_name, family, version, enabled, is_default, applicable_demand_type, parameters, description)
values
  ('MA_3M', '3개월 이동평균', 'MOVING_AVERAGE', '1.0.0', true, true, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"window":3}', '최근 3개월 학습 수요 평균'),
  ('MA_6M', '6개월 이동평균', 'MOVING_AVERAGE', '1.0.0', true, false, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"window":6}', '최근 6개월 학습 수요 평균'),
  ('WMA_3M', '가중 3개월 이동평균', 'WEIGHTED_MOVING_AVERAGE', '1.0.0', true, false, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"weight_recent":3,"weight_middle":2,"weight_oldest":1}', '최근순 3:2:1 가중 평균'),
  ('PY_SAME_MONTH', '전년 동월', 'SEASONAL_NAIVE', '1.0.0', true, false, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"lag_months":12}', '전년 동월 실제 학습 수요'),
  ('SEASONAL_NAIVE', '계절 순진 예측', 'SEASONAL_NAIVE', '1.0.0', true, false, array['SMOOTH','INTERMITTENT','ERRATIC','LUMPY'], '{"season_months":12}', '가장 최근 동일 월 학습 수요')
on conflict (model_id) do nothing;

create table if not exists core.model_version (
  model_version_id bigint generated by default as identity primary key,
  run_id uuid,
  model_id text not null references core.model_config(model_id),
  version text not null,
  parameters jsonb not null,
  definition jsonb not null,
  snapshotted_at timestamptz not null default now(),
  unique(run_id, model_id)
);

create table if not exists core.forecast_run (
  run_id uuid primary key default gen_random_uuid(),
  status text not null default 'RUNNING' check (status in ('RUNNING','SUCCESS','FAILED')),
  granularity text not null,
  train_start date not null,
  train_end date not null,
  horizon integer not null,
  champion_metric text,
  data_snapshot_at timestamptz not null,
  models jsonb not null default '[]'::jsonb,
  n_models integer not null default 0,
  n_items integer not null default 0,
  n_rows integer not null default 0,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms bigint,
  triggered_by uuid references auth.users(id) on delete set null,
  triggered_email text,
  note text,
  message text
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'model_version_run_id_fkey') then
    alter table core.model_version add constraint model_version_run_id_fkey foreign key (run_id) references core.forecast_run(run_id) on delete cascade;
  end if;
end $$;

create table if not exists core.forecast_result (
  run_id uuid not null references core.forecast_run(run_id) on delete cascade,
  model_id text not null references core.model_config(model_id),
  item_id text not null,
  period date not null,
  model_version text not null,
  predicted_qty numeric,
  p50 numeric,
  p80 numeric,
  p90 numeric,
  sigma numeric,
  basis text not null,
  calculation_status text not null default 'SUCCESS' check (calculation_status in ('SUCCESS','CALCULATION_UNAVAILABLE')),
  reason_code text,
  created_at timestamptz not null default now(),
  primary key(run_id, model_id, item_id, period)
);

create index if not exists forecast_result_run_idx on core.forecast_result(run_id, period);
create index if not exists forecast_run_started_idx on core.forecast_run(started_at desc);

create or replace view core.v_train_monthly_demand as
with setting as (
  select train_start, train_end from core.forecast_setting where setting_key = 'default'
), periods as (
  select generated.period_start::date as period_start
  from setting,
       generate_series(date_trunc('month', train_start::timestamp), date_trunc('month', train_end::timestamp), interval '1 month') generated(period_start)
  where train_start is not null and train_end is not null
), items as (
  select item_id from core.v_item_master group by item_id
), monthly as (
  select upper(regexp_replace(item_id, '[\s\-_]', '', 'g')) as item_id,
         date_trunc('month', use_date)::date as period_start,
         sum(qty) as quantity
  from core.v_train_demand
  group by 1,2
)
select i.item_id, p.period_start, m.quantity
from items i cross join periods p
left join monthly m using(item_id, period_start);

create or replace function core.baseline_point(p_model_id text, p_item_id text, p_target_period date, p_parameters jsonb)
returns numeric
language plpgsql
stable
set search_path = core, public
as $$
declare
  result numeric;
  window_size integer;
  recent_weight numeric;
  middle_weight numeric;
  oldest_weight numeric;
  lag_months integer;
  season_months integer;
begin
  if p_model_id in ('MA_3M','MA_6M') then
    window_size := coalesce((p_parameters->>'window')::integer, case when p_model_id = 'MA_3M' then 3 else 6 end);
    select case when count(quantity) = window_size then avg(quantity) else null end into result
    from (select quantity from core.v_train_monthly_demand where item_id = p_item_id and period_start < p_target_period order by period_start desc limit window_size) source;
    return result;
  end if;
  if p_model_id = 'WMA_3M' then
    recent_weight := coalesce((p_parameters->>'weight_recent')::numeric, 3);
    middle_weight := coalesce((p_parameters->>'weight_middle')::numeric, 2);
    oldest_weight := coalesce((p_parameters->>'weight_oldest')::numeric, 1);
    select case when count(quantity) = 3 then sum(quantity * case rn when 1 then recent_weight when 2 then middle_weight else oldest_weight end) / sum(case rn when 1 then recent_weight when 2 then middle_weight else oldest_weight end) else null end into result
    from (select quantity, row_number() over(order by period_start desc) as rn from core.v_train_monthly_demand where item_id = p_item_id and period_start < p_target_period order by period_start desc limit 3) source;
    return result;
  end if;
  if p_model_id = 'PY_SAME_MONTH' then
    lag_months := coalesce((p_parameters->>'lag_months')::integer, 12);
    select quantity into result from core.v_train_monthly_demand where item_id = p_item_id and period_start = (p_target_period - make_interval(months => lag_months))::date;
    return result;
  end if;
  if p_model_id = 'SEASONAL_NAIVE' then
    season_months := coalesce((p_parameters->>'season_months')::integer, 12);
    select quantity into result from core.v_train_monthly_demand where item_id = p_item_id and period_start < p_target_period and extract(month from period_start) = extract(month from p_target_period) order by period_start desc limit 1;
    return result;
  end if;
  return null;
end;
$$;

create or replace function core.run_baseline_forecast(p_note text default null)
returns uuid
language plpgsql
security definer
set search_path = core, public
as $$
declare
  new_run_id uuid := gen_random_uuid();
  actor_id uuid := auth.uid();
  actor_email text;
  setting_row core.forecast_setting%rowtype;
  model_row core.model_config%rowtype;
  profile_row record;
  future_period date;
  point numeric;
  sigma numeric;
  snapshot_at timestamptz;
  model_ids jsonb := '[]'::jsonb;
  item_count integer := 0;
  result_count integer := 0;
  start_clock timestamptz := clock_timestamp();
begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select * into setting_row from core.forecast_setting where setting_key = 'default';
  if setting_row.train_start is null or setting_row.train_end is null then raise exception 'FORECAST_SETTING_INCOMPLETE'; end if;
  select email into actor_email from auth.users where id = actor_id;
  select coalesce(max(loaded_at), clock_timestamp()) into snapshot_at from core.v_train_demand;
  insert into core.forecast_run(run_id, status, granularity, train_start, train_end, horizon, data_snapshot_at, triggered_by, triggered_email, note)
  values(new_run_id, 'RUNNING', setting_row.granularity, setting_row.train_start, setting_row.train_end, setting_row.forecast_horizon, snapshot_at, actor_id, actor_email, p_note);
  begin
    for model_row in select * from core.model_config where enabled order by model_id loop
      model_ids := model_ids || jsonb_build_object('model_id', model_row.model_id, 'version', model_row.version, 'parameters', model_row.parameters, 'definition', jsonb_build_object('model_name', model_row.model_name, 'family', model_row.family, 'engine', model_row.engine, 'applicable_demand_type', model_row.applicable_demand_type));
      insert into core.model_version(run_id, model_id, version, parameters, definition) values(new_run_id, model_row.model_id, model_row.version, model_row.parameters, jsonb_build_object('model_name', model_row.model_name, 'family', model_row.family, 'engine', model_row.engine, 'applicable_demand_type', model_row.applicable_demand_type));
      for profile_row in execute format('select item_id, demand_type from analytics.v_sku_demand_profile where demand_type = any($1)') using model_row.applicable_demand_type loop
        item_count := item_count + 1;
        for future_period in select generated::date from generate_series((setting_row.train_end + interval '1 month')::date, (setting_row.train_end + make_interval(months => setting_row.forecast_horizon))::date, interval '1 month') generated loop
          point := core.baseline_point(model_row.model_id, profile_row.item_id, future_period, model_row.parameters);
          select case when count(residual) >= 2 then stddev_samp(residual) else null end into sigma from (
            select quantity - core.baseline_point(model_row.model_id, item_id, period_start, model_row.parameters) as residual
            from core.v_train_monthly_demand where item_id = profile_row.item_id and quantity is not null
          ) residuals where residual is not null;
          insert into core.forecast_result(run_id, model_id, item_id, period, model_version, predicted_qty, p50, p80, p90, sigma, basis, calculation_status, reason_code)
          values(new_run_id, model_row.model_id, profile_row.item_id, future_period, model_row.version, point, point, case when point is not null and sigma is not null then point + sigma * 0.841621 else null end, case when point is not null and sigma is not null then point + sigma * 1.281552 else null end, sigma, model_row.model_id || ' · train only', case when point is null then 'CALCULATION_UNAVAILABLE' else 'SUCCESS' end, case when point is null then 'INSUFFICIENT_HISTORY' when sigma is null then 'SIGMA_UNAVAILABLE' else null end);
          result_count := result_count + 1;
        end loop;
      end loop;
    end loop;
    update core.forecast_run set status = 'SUCCESS', models = model_ids, n_models = jsonb_array_length(model_ids), n_items = (select count(distinct item_id) from core.forecast_result where run_id = new_run_id), n_rows = result_count, finished_at = clock_timestamp(), duration_ms = (extract(epoch from (clock_timestamp() - start_clock)) * 1000)::bigint, message = 'BASELINE_SUCCESS' where run_id = new_run_id;
    update core.forecast_data_state set stale = false, data_snapshot_at = snapshot_at, stale_reason = null, updated_at = clock_timestamp() where state_key = 'default';
  exception when others then
    update core.forecast_run set status = 'FAILED', models = model_ids, n_models = jsonb_array_length(model_ids), n_items = (select count(distinct item_id) from core.forecast_result where run_id = new_run_id), n_rows = result_count, finished_at = clock_timestamp(), duration_ms = (extract(epoch from (clock_timestamp() - start_clock)) * 1000)::bigint, message = sqlerrm where run_id = new_run_id;
  end;
  return new_run_id;
end;
$$;

create or replace view analytics.v_model_config as select * from core.model_config;
create or replace view analytics.v_forecast_run as
select r.*, (coalesce(s.stale, false) or coalesce((select max(loaded_at) from core.v_train_demand) > r.data_snapshot_at, false)) as is_stale
from core.forecast_run r cross join core.forecast_data_state s where s.state_key = 'default';
create or replace view analytics.v_forecast_result as select * from core.forecast_result;
create or replace view analytics.v_forecast_run_kpi as
select run_id, count(distinct model_id)::integer as n_models, count(distinct item_id)::integer as n_items, count(*)::integer as n_rows, count(*) filter(where calculation_status = 'SUCCESS')::integer as n_calculated, count(*) filter(where calculation_status = 'CALCULATION_UNAVAILABLE')::integer as n_calculation_unavailable
from core.forecast_result group by run_id;

alter table core.model_config enable row level security;
alter table core.model_version enable row level security;
alter table core.forecast_run enable row level security;
alter table core.forecast_result enable row level security;
drop policy if exists model_config_authenticated_select on core.model_config;
create policy model_config_authenticated_select on core.model_config for select to authenticated using (true);
drop policy if exists model_config_admin_write on core.model_config;
create policy model_config_admin_write on core.model_config for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists model_version_authenticated_select on core.model_version;
create policy model_version_authenticated_select on core.model_version for select to authenticated using (true);
drop policy if exists forecast_run_authenticated_select on core.forecast_run;
create policy forecast_run_authenticated_select on core.forecast_run for select to authenticated using (true);
drop policy if exists forecast_result_authenticated_select on core.forecast_result;
create policy forecast_result_authenticated_select on core.forecast_result for select to authenticated using (true);

grant usage on schema core, analytics to authenticated;
grant select on analytics.v_model_config, analytics.v_forecast_run, analytics.v_forecast_result, analytics.v_forecast_run_kpi to authenticated;
grant select on core.model_config, core.model_version, core.forecast_run, core.forecast_result to authenticated;
grant update on core.model_config to authenticated;
grant execute on function core.run_baseline_forecast(text) to authenticated;
revoke all on analytics.v_model_config, analytics.v_forecast_run, analytics.v_forecast_result, analytics.v_forecast_run_kpi from anon;
