-- STEP2 인증·Role·RBAC 기반
-- auth.users는 Supabase Auth가 관리하므로 업무 사용자와 감사 로그만 core에 둡니다.

create schema if not exists core;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  department text not null default '',
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create index if not exists app_user_role_active_idx on core.app_user(role, active);
create index if not exists audit_log_target_idx on core.audit_log(target_type, target_id, at desc);

create or replace function core.is_admin()
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select exists (
    select 1 from core.app_user
    where user_id = auth.uid() and role = 'ADMIN' and active = true
  );
$$;

revoke all on function core.is_admin() from public;
grant execute on function core.is_admin() to anon, authenticated;

create or replace function core.set_app_user_updated_at()
returns trigger
language plpgsql
set search_path = core, public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function core.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = core, public
as $$
begin
  insert into core.app_user(user_id, email, name, department)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.raw_user_meta_data ->> 'department', '')
  )
  on conflict (user_id) do update set email = excluded.email, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_app_user on auth.users;
create trigger on_auth_user_created_app_user
  after insert on auth.users
  for each row execute function core.handle_new_auth_user();

create or replace function core.audit_app_user_change()
returns trigger
language plpgsql
security definer
set search_path = core, public
as $$
begin
  if (old.role is distinct from new.role or old.active is distinct from new.active) then
    if old.user_id = auth.uid() and old.role is distinct from new.role then
      raise exception 'SELF_ROLE_CHANGE_FORBIDDEN';
    end if;
    if old.user_id = auth.uid() and old.active is distinct from new.active then
      raise exception 'SELF_ACTIVE_CHANGE_FORBIDDEN';
    end if;
    insert into core.audit_log(actor, action, target_type, target_id, before, after)
    values (auth.uid(), 'APP_USER_UPDATED', 'app_user', new.user_id::text, to_jsonb(old), to_jsonb(new));
  end if;
  return new;
end;
$$;

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at before update on core.app_user for each row execute function core.set_app_user_updated_at();
drop trigger if exists app_user_audit_change on core.app_user;
create trigger app_user_audit_change after update on core.app_user for each row execute function core.audit_app_user_change();

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;

drop policy if exists "app_user_self_or_admin_select" on core.app_user;
create policy "app_user_self_or_admin_select" on core.app_user for select to authenticated
  using (user_id = auth.uid() or core.is_admin());
drop policy if exists "app_user_admin_update" on core.app_user;
create policy "app_user_admin_update" on core.app_user for update to authenticated
  using (core.is_admin()) with check (core.is_admin());
drop policy if exists "audit_log_admin_select" on core.audit_log;
create policy "audit_log_admin_select" on core.audit_log for select to authenticated
  using (core.is_admin());

revoke all on core.app_user from anon;
revoke all on core.audit_log from anon;
revoke insert, update, delete on core.app_user from anon, authenticated;
grant select on core.app_user to authenticated;
grant update on core.app_user to authenticated;
revoke all on core.audit_log from anon, authenticated;
grant select on core.audit_log to authenticated;

-- 기존 수업용 전체 허용 정책과 anon 쓰기 권한을 제거합니다.
drop policy if exists "수업용 전체 허용" on core.leadtime_plan;
drop policy if exists "수업용 전체 허용" on core.usage_profile;
revoke insert, update, delete on core.leadtime_plan from anon, authenticated;
revoke insert, update, delete on core.usage_profile from anon, authenticated;
drop policy if exists "leadtime_plan_authenticated_select" on core.leadtime_plan;
drop policy if exists "usage_profile_authenticated_select" on core.usage_profile;
drop policy if exists "leadtime_plan_admin_write" on core.leadtime_plan;
drop policy if exists "usage_profile_admin_write" on core.usage_profile;
create policy "leadtime_plan_authenticated_select" on core.leadtime_plan for select to authenticated using (true);
create policy "usage_profile_authenticated_select" on core.usage_profile for select to authenticated using (true);
create policy "leadtime_plan_admin_write" on core.leadtime_plan for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy "usage_profile_admin_write" on core.usage_profile for all to authenticated using (core.is_admin()) with check (core.is_admin());

revoke usage on schema core from anon;
revoke all on all tables in schema core from anon;
grant usage on schema core to authenticated;
grant select on all tables in schema analytics to authenticated;
revoke all on all tables in schema analytics from anon;
revoke usage on schema analytics from anon;
